services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: observiply-akips-datasource
      GF_LOG_FILTERS: plugin.observiply-akips-datasource:debug
